options:
  checksum:
    type: string
    default: "98f0868c0cf9fc6664b57f89149fa537b73222bcc010247771e4afc08c8199fd"
    description: "Dokuwiki sha256 checksum"
  host:
    description: Host to be passed to php-fpm interface
    type: string
    default: 0.0.0.0
  port:
    description: Port to be passed to php-fpm interface
    type: int
    default: 9000